
services:
  jupyterhub:
    build: .
    container_name: jupyterhub-rtc
    ports:
      - "8000:8000"
    volumes:
      - ./data:/srv/jupyterhub   # persists user notebooks/configs
      - ./userhomes:/home
      - ./init-users.sh:/usr/local/bin/init-users.sh

